language: node_js
dist: precise
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - '280304286@163.com'
    on_success: always # default: change
    on_failure: always # default: always
node_js:
  - '8'
before_script:
script:
  - npm run test
after_success:
  - npm run ci-demo-release
  - npm run ci-docs-release
  - npm run ci-report-coverage
  - npm run ci-github-release
